parser: typescript-eslint-parser
plugins:
  - typescript
  - babel
  - react
extends:
  - prettier
  - prettier/react

rules:
  ##########
  # CUSTOM #
  ##########
  insecure-random: error

  ###########
  # PLUGINS #
  ###########
  # TYPESCRIPT
  typescript/interface-name-prefix:
    - error
    - always
  typescript/explicit-member-accessibility: error
  typescript/no-unused-vars: error
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/pull/23
  # typescript/member-ordering: error
  ##

  # Babel
  babel/no-invalid-this: error

  # React
  react/jsx-boolean-value:
    - error
    - always
  react/jsx-key: error
  react/jsx-no-bind: error
  react/no-string-refs: error

  ###########
  # BUILTIN #
  ###########
  curly: error
  no-new-wrappers: error
  no-redeclare:
    - error
    - builtinGlobals: true
  no-eval: error
  no-sync: error
  no-unused-expressions: error
  no-use-before-define:
    - error
    - functions: false
      variables: false
  no-var: error
  prefer-const: error
  eqeqeq:
    - error
    - smart

  ###########
  # SPECIAL #
  ###########
  no-restricted-syntax:
    - error
    # no-default-export
    - selector: ExportDefaultDeclaration
      message: Use of default exports is forbidden

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
