notifications:
  email:
    on_success: never
    on_failure: change

dist: trusty

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      # by default the container VMs have Git 1.9.1, ermagherd...
      - git-all
      # this is required to compile keytar
      - libsecret-1-dev
      # this package is essential for testing Electron in a headless fashion
      # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
      - xvfb

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "7"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install -g yarn@1.1.0
  - yarn

script:
  - yarn check-prettiness
  - yarn lint
  - yarn build:prod
  - yarn test:setup
  - yarn test

after_failure:
  - yarn test:review
