notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    

language: node_js
node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
