notifications:
  email:
    on_success: never
    on_failure: change

os:
  - osx

branches:
  only:
    - master

language: node_js
node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build:prod
  - npm test

after_success:
  - node script/publish
