notifications:
  email:
    on_success: never
    on_failure: change

os:
  - osx

branches:
  only:
    - master
    - /^__release-.*/

language: node_js
node_js:
  - "node"

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install

before_script:
  - KEY_CHAIN=build.keychain
  - security create-keychain -p travis $KEY_CHAIN
  - security default-keychain -s $KEY_CHAIN
  - security unlock-keychain -p travis $KEY_CHAIN
  - security set-keychain-settings -t 3600 -u $KEY_CHAIN

script:
  - npm run lint
  - npm run build:prod
  - npm run test:unit
  - npm run test:integration

after_success:
  - npm run publish
