os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "6"

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node -e "console.log(process.arch)"
  - npm install -g npm
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:PRIVATE_KEY.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
  - git submodule update --init --recursive
  - npm install

build_script:
  - npm run lint
  - npm run build:prod

test_script:
  - npm test

on_success:
  - npm run publish
