environment:
  nodejs_version: "5"

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build:
  - npm run lint
  - npm run build

test_script:
  - npm test

cache:
  - node_modules
