environment:
  nodejs_version: "6"

cache:
  - node_modules

branches:
  only:
    - master
    - /^__release-.*/

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install node-gyp@3.4.0

build_script:
  - npm run lint
  - npm run build:prod

test_script:
  - npm test

on_success:
  - node script/publish
